"""Generate colab/run_all.py: ONE self-contained file that does the whole job.

The first attempt failed for a boring reason: a Colab VM is reclaimed when it is idle, and I
claimed one and then let it sit while fixing code. This bundles everything so the VM is busy from
the instant it is granted until it is done, and needs no second upload.

It vendors the three already-tested files verbatim (base64, digests checked on write) rather than
copying their logic, so what runs on the VM is exactly what runs here:

  payload.py       the brain modules + curriculum, so no git clone is needed (no remote exists)
  step1_build.py   fetch the public sources, build the graph, GATE the accelerator
  step2_measure.py the four-arm comparison that saves checkpoints and recomputes its own numbers

Run:  python gen_colab_single.py
"""
from __future__ import annotations

import base64
import hashlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
FLY = HERE.parent
FILES = {
    "payload.py": FLY / "tools" / "payload.py",
    "step1_build.py": FLY / "colab" / "step1_build.py",
    "step2_measure.py": FLY / "colab" / "step2_measure.py",
}
OUT = FLY / "colab" / "run_all.py"


def main() -> None:
    blobs, digests = {}, {}
    for name, path in FILES.items():
        raw = path.read_bytes()
        blobs[name] = base64.b64encode(raw).decode("ascii")
        digests[name] = hashlib.sha256(raw).hexdigest()
        print(f"  {name}: {len(raw)} bytes  {digests[name][:16]}...")

    body = "\n".join(f"    {n!r}: {b!r}," for n, b in blobs.items())
    text = f'''"""FlyLingo on Colab, end to end, in one file. GENERATED by tools/gen_colab_single.py.

Embeds the three tested scripts verbatim and runs them back to back, so the VM never sits idle
between steps. Run it on a GPU machine:

    colab run --gpu T4 --keep run_all.py 40 5 10      # epochs seeds tail
"""
from __future__ import annotations

import base64
import hashlib
import os
import runpy
import subprocess
import sys
import time
from pathlib import Path

FILES = {{
{body}
}}

DIGESTS = {digests!r}
CONTENT = Path("/content")
ROOT = CONTENT / "flylingo"


def materialise() -> None:
    for name, blob in FILES.items():
        raw = base64.b64decode(blob)
        got = hashlib.sha256(raw).hexdigest()
        if got != DIGESTS[name]:
            raise SystemExit(f"{{name}} decoded to sha256 {{got}}, expected {{DIGESTS[name]}}")
        (CONTENT / name).write_bytes(raw)
        print(f"  materialised {{name}} ({{len(raw)}} bytes)", flush=True)


def main() -> None:
    t0 = time.time()
    print("=" * 74)
    print("FlyLingo on Colab -- full run: graph, gate, four-arm measurement")
    print("=" * 74, flush=True)
    materialise()

    print("\\n--- step 1: sources, graph, accelerator gate ---", flush=True)
    sys.argv = ["step1_build.py"]
    runpy.run_path(str(CONTENT / "step1_build.py"), run_name="__main__")

    print("\\n--- step 2: the four-arm measurement ---", flush=True)
    # step 2 reads ROOT, GRAPH and RUNS from the environment so the same file works here and
    # locally; on Colab the defaults under /content/flylingo are correct.
    os.environ.setdefault("FLYLINGO_ROOT", str(ROOT))
    args = sys.argv[1:] if len(sys.argv) > 1 else ["40", "5", "10"]
    while len(args) < 3:
        args.append({{0: "40", 1: "5"}}[len(args)])
    sys.argv = ["step2_measure.py", *args]
    runpy.run_path(str(CONTENT / "step2_measure.py"), run_name="__main__")

    print(f"\\nALL DONE in {{(time.time() - t0) / 60:.1f}} min", flush=True)
    print("results: /content/flylingo/runs/plastic_brain/", flush=True)
    subprocess.run("ls -la /content/flylingo/runs/plastic_brain/ | tail -25", shell=True)


if __name__ == "__main__":
    main()
'''
    OUT.write_text(text, encoding="utf-8")
    print(f"\nwrote {OUT}  ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
