"""Copy the two visualization harnesses into the app.

`viz-fly/` and `viz-brain/` are standalone Vite projects so they can be developed and
loaded on their own. The Next app needs the same components, and Next cannot import
from a sibling project root cleanly, so this script copies their `src` trees into
`duolingo-clone/components/viz/`.

The standalone harnesses remain the source of truth. Run this after changing them:

    python tools/sync_viz.py

Both copies are generated files. Do not edit them in place.
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(r"D:\Projects\flylingo")
DEST = ROOT / "duolingo-clone" / "components" / "viz"

HEADER = """// GENERATED by tools/sync_viz.py from {src}. Do not edit here.
"""

PAIRS = [
    ("viz-fly", "fly"),
    ("viz-brain", "brain"),
]


def main() -> int:
    failures = []
    DEST.mkdir(parents=True, exist_ok=True)
    for project, name in PAIRS:
        src = ROOT / project / "src"
        if not src.is_dir():
            failures.append(f"{project}/src is missing")
            continue
        out = DEST / name
        if out.exists():
            shutil.rmtree(out)
        shutil.copytree(src, out, ignore=shutil.ignore_patterns("*.test.*", "*.map"))
        copied = sum(1 for _ in out.rglob("*") if _.is_file())
        print(f"{project}/src -> components/viz/{name} ({copied} files)")

    if failures:
        for f in failures:
            print("FAILED:", f, file=sys.stderr)
        return 1
    print("\nSynced. The app imports these via @/components/viz/...")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
